### PR TITLE
Add method for query cancellation

### PR DESCRIPTION
**Pull request by tom4zelli**
Permitir o uso de cancelOperation, expondo diretamente na interface Attachment.

### CODE REVIEW

**Comment by asfernandes** [comment]
The driver should better avoid recreating weirdness of Firebird interfaces, so it would be better to split the function in two:
- One that do fb_cancel_disable / fb_cancel_enable thing
- One that do fb_cancel_raise / fb_cancel_abort thing

**Comment by tom4zelli** [comment]
Ok, could it be something like this?

cancelOperationEnable/cancelEnable(value:boolean)
- value = true -> fb_cancel_enable
- value = false -> fb_cancel_disable
and
cancelOperation(abort:boolean)
- abort = false -> fb_cancel_raise
- abort = true -> fb_cancel_abort

**Comment by tom4zelli** [comment]
Captura de tela de 2023-02-25 10-14-56

**Comment by asfernandes** [comment]
Can you write tests for it?
Also, please follow the coding style using spaces appropriately, example: no `var?1:2` but `var ? 1 : 2`

**Comment by tom4zelli** [comment]
ok, sorry, my first contribution with git projects, I'm not yet familiar with norms and patterns...

**Comment by asfernandes** [comment]
I did some rework in your solution in branch https://github.com/asfernandes/node-firebird-drivers/tree/work/cancellation
Please review and test.

**Comment by tom4zelli** [comment]
Tested and it's ok!!!

**Comment by tom4zelli** [comment]
thanks!!!,
can you guide me if i should do anything else? I need to finalize something, should I do a "close pull request"?

**Comment by asfernandes** [comment]
> thanks!!!, can you guide me if i should do anything else? I need to finalize something, should I do a "close pull request"?

Please maintain the PR open for now, it should change automatically to merge when I merge the branch I created with your commits included.

**Comment by asfernandes** [comment]
Merged in master.

**Pull request closed without merging**
